"""
In this script, we will use vowels but stop consonant tags to evaluate the model. 
This is because stops are short and listeners usually use acoustic cues from the vowel 
to identify the stop consonant. We will check whether the model also did the same. 
"""

from cgi import test
from tkinter import E
import warnings
from xml.etree.ElementInclude import include
warnings.simplefilter(action='ignore', category=FutureWarning)

from C_0X_defs import *
from C_0Y_evaldefs import *
from E_0X_evaldefs import *
import plotly.graph_objs as go
import plotly.express as px
from colorama import Fore, Back, Style

#########################################################################################################
#############################################Main Script ################################################
#########################################################################################################
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='argparse')
    parser.add_argument('--timestamp', '-ts', type=str, default="0000000000", help="Timestamp for project, better be generated by bash")
    parser.add_argument('--gpu', '-gpu', type=int, default=0, help="Choose the GPU to work on")
    parser.add_argument('--model','-m',type=str, default = "ae",help="Model type: ae or vqvae")
    parser.add_argument('--condition','-cd',type=str, default="b", help='Condition: b (balanced), u (unbalanced), nt (no-T)')
    parser.add_argument('--zlevel','-zl',type=str, default="hidrep", help='hidrep / attnout')
    parser.add_argument('--testname','-tn',type=str, default="abx-vowelstop", help='')
    args = parser.parse_args()

    # set device number
    torch.cuda.set_device(args.gpu)
    test_name = args.testname

    ts = args.timestamp # this timestamp does not contain run number
    train_name = "E_0A"
    res_save_dir = os.path.join(model_save_, f"eval-{train_name}-{ts}")
    model_type = args.model
    model_condition = args.condition
    zlevel = args.zlevel
    model_condition_dir = os.path.join(res_save_dir, model_type, model_condition)
    print(model_condition_dir)
    assert PU.path_exist(model_condition_dir)
    this_save_dir = os.path.join(model_condition_dir, "integrated_results")
    mk(this_save_dir)

    the_good_saving_dir = os.path.join(res_save_dir, test_name)
    mk(the_good_saving_dir)
    the_good_saving_dir_model_condition = os.path.join(res_save_dir, test_name, model_condition, model_type)
    mk(the_good_saving_dir_model_condition)

    hidden_dim = int(model_type.split("-")[0].replace("recon", "")) # get hidden dimension from model_type
    learned_runs = [1, 2, 3, 4, 5]
    string_learned_runs = [str(num) for num in learned_runs]
    strseq_learned_runs = "".join(string_learned_runs)

    stop_list_epochs = [] # list for each epoch of lists of sse for each run
    asp_list_epochs = []

    # This will be changed according to the environment
    st_condition_name = "Sh"
    t_condition_name = "S"

    abx_num_samples = 20

    if test_name.split("-")[0] in ["clusterSomething"]: 
        hidden_dim_use = hidden_dim
        # 1 is euclidean, 2 is cosine distance
        # this one evaluates the copntrast between p, p(h) and (p)h. 
        for epoch in range(0, 101): 
            # 先循环epoch，再循环run
            stop_list_runs = []
            asp_list_runs = []
            print(f"Processing {model_type} in epoch {epoch}...")
            for run_number in learned_runs:

                test_name_lookat = test_name.split("-")[1]
                test_name_label = test_name.split("-")[2]
                test_name_datasource = test_name.split("-")[3]


                this_model_condition_dir = os.path.join(model_condition_dir, f"{run_number}")
                hidrep_handler = DictResHandler(whole_res_dir=this_model_condition_dir, 
                                    file_prefix=f"all-{epoch}")
                hidrep_handler.read()
                hidrep = hidrep_handler.res
                # select representation to work on
                other_hid_outs = hidrep["other-hid-outs"]
                if zlevel == "hidrep": 
                    all_zq = hidrep["ze"]
                elif zlevel == "attnout": 
                    all_zq = hidrep["zq"]
                elif zlevel == "ori": 
                    if hidden_dim != model_configs["ori_select_dim"]: 
                        raise Exception("Warning: hidden_dim is not 64, but we are using the original representation! ")
                    all_zq = hidrep["ori"]
                    hidden_dim_use = model_configs["hiddim"]
                elif zlevel in other_hid_outs.keys(): 
                    all_zq = other_hid_outs[zlevel]
                else: 
                    raise ValueError("zlevel must be one of 'hidrep' or 'attnout'")
                
                all_sepframes1 = hidrep["sep-frame1"]
                all_sepframes2 = hidrep["sep-frame2"]
                all_phi_type = hidrep["phi-type"]
                all_v1_names = hidrep["v1-name"]
                all_s_names = hidrep["sn"]
                all_v2_names = hidrep["vn"]

                include_map = None
                include_tags = None
                this_offset = (0, 0.3)
                this_auxon = None
                merge_one_vector = False
                if test_name_datasource == "gender": 
                    all_datasource = hidrep["gender"]
                elif test_name_datasource == "speaker": 
                    all_datasource = hidrep["sid"]
                elif test_name_datasource == "POA": 
                    all_datasource = hidrep["sn"]
                elif test_name_datasource == "vowel1": 
                    all_datasource = hidrep["vn"]
                    include_tags = ["AA", "IY"] # NOTE: not changed! 
                elif test_name_datasource == "SSH":
                    # test whether the vowels can distinguish the S/SH contrast. 
                    all_datasource = all_s_names
                else: 
                    raise ValueError("Datasource not included! ")
                
                merge_one_vector = False
                # Select Vowels and Vowel Tags
                hidr_p, tags_p = get_toplot(hiddens=all_zq, 
                                                sepframes1=all_sepframes1,
                                                sepframes2=all_sepframes2,
                                                phi_types=all_phi_type,
                                                stop_names=all_datasource,
                                                offsets=this_offset, 
                                                contrast_in=test_name_label, 
                                                merge=merge_one_vector, 
                                                hidden_dim=hidden_dim_use, 
                                                lookat=test_name_lookat, 
                                                include_map=include_map, 
                                                aux_on=this_auxon)
                # combine them
                # hidr_cs, tags_cs = np.concatenate((hidr_p, hidr_pp, hidr_h), axis=0), np.concatenate((tags_p, tags_pp, tags_h), axis=0)
                hidr_cs, tags_cs = hidr_p, tags_p
                hidr_cs, tags_cs, nannum = postproc_standardize(hidr_cs, tags_cs, outlier_ratio=0.5, denan=True)
                print(f"{model_type}@{epoch} in run {run_number}: {nannum}")

                kmeans = KMeans(n_clusters=8, random_state=0)
                predicted_labels = kmeans.fit_predict(hidr_cs)
                ari = adjusted_rand_score(tags_cs, predicted_labels)
                asp_list_runs.append(ari)

            asp_list_epochs.append(asp_list_runs)

        asp_list_epochs = np.array(asp_list_epochs)
        asp_list_epochs = asp_list_epochs.transpose(1, 0)
        # plot_silhouette(asp_list_epochs, stop_list_epochs, os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"))
        plot_many([asp_list_epochs], ["ARI"], 
                  os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"), 
                  {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  y_range=(0, 1.0))
        np.save(os.path.join(res_save_dir, test_name, f"07-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        print("Done.")

    elif test_name.split("-")[0] in ["clusterSomethingAll"]: 
        # 1 is euclidean, 2 is cosine distance
        # this one evaluates the copntrast between p, p(h) and (p)h.
        # 'dec-lin1' 'enc-rnn1-f' 'enc-rnn1-b' 'dec-rnn1-f' 'enc-rnn2-f' 'enc-rnn2-b' 'dec-rnn2-f' 
        look_for_layer_path = test_name.split("-")[0][:-3] + "-" + test_name.split("-")[1] + "-" + test_name.split("-")[2] + "-" + test_name.split("-")[3]
        layered_res = {}
        # deal with ori
        ori_path = os.path.join(res_save_dir, look_for_layer_path, f"07-save-ari-recon{model_configs['ori_select_dim']}-phi-{model_condition}-{strseq_learned_runs}-ori.npy")
        if os.path.exists(ori_path): 
            ori_res = np.load(ori_path)
            layered_res["ori"] = ori_res
        else: 
            raise ValueError("No ori path found.")
        
        for layer in ["hidrep", "attnout", "dec-lin1", "enc-lin1", 
                      "dec-rnn1-f", "enc-rnn1-f", "enc-rnn1-b",
                      "dec-rnn2-f", "enc-rnn2-f", "enc-rnn2-b", 
                      "dec-rnn3-f", "enc-rnn3-f", "enc-rnn3-b", 
                      "dec-rnn4-f", "enc-rnn4-f", "enc-rnn4-b", 
                      "dec-rnn5-f", "enc-rnn5-f", "enc-rnn5-b", ]: # "enc-lin1", 
            print(f"Processing {model_type} in layer {layer}...")
            asp_list_epochs = []
            layer_path = os.path.join(res_save_dir, look_for_layer_path, 
                                      f"07-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{layer}.npy")
            if os.path.exists(layer_path): 
                layer_res = np.load(layer_path)
            else: 
                print(f"Warning: {layer_path} not found. ")
                layer_res = np.zeros_like(ori_res)
            layered_res[layer] = layer_res
        layered_res["ori"] = ori_res
        plot_many_plotly(list(layered_res.values()), list(layered_res.keys()), 
                  os.path.join(res_save_dir, test_name, f"08-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.html"), 
                  {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  y_range=(0, 0.2), cloud=False)
        # np.save(os.path.join(res_save_dir, test_name, f"04-save-ptk-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), stop_list_epochs)
        # np.save(os.path.join(res_save_dir, test_name, f"05-save-asp-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        # with open(os.path.join(res_save_dir, test_name, f"06-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.pkl"), "wb") as f: 
        #     pickle.dump(layered_res, f)
        print("Done.")

    elif test_name.split("-")[0] in ["ABXSomething"]: 
        # 1 is euclidean, 2 is cosine distance
        # this one evaluates the copntrast between p, p(h) and (p)h. 
        hidden_dim_use = hidden_dim
        for epoch in range(0, 101): 
            # 先循环epoch，再循环run
            stop_list_runs = []
            asp_list_runs = []
            print(f"Processing {model_type} in epoch {epoch}...")
            for run_number in learned_runs:

                test_name_lookat = test_name.split("-")[1]
                test_name_label = test_name.split("-")[2]
                test_name_datasource = test_name.split("-")[3]

                this_model_condition_dir = os.path.join(model_condition_dir, f"{run_number}")
                hidrep_handler = DictResHandler(whole_res_dir=this_model_condition_dir, 
                                    file_prefix=f"all-{epoch}")
                hidrep_handler.read()
                hidrep = hidrep_handler.res
                # select representation to work on
                all_representations, hidden_dim_use = get_representation(data_collection=hidrep, 
                                                         representation_select=zlevel, 
                                                         hidden_dim_required=hidden_dim)
                
                all_sepframes1 = hidrep["sep-frame1"]
                all_sepframes2 = hidrep["sep-frame2"]
                all_phi_type = hidrep["phi-type"]
                all_v1_names = hidrep["v1-name"]
                all_s_names = hidrep["sn"]
                all_v2_names = hidrep["vn"]


                include_map = None
                include_tags = None
                this_offset = (0.4, 0.6)
                this_auxon = None
                merge_one_vector = False
                if test_name_datasource == "gender": 
                    all_datasource = hidrep["gender"]
                elif test_name_datasource == "speaker": 
                    all_datasource = hidrep["sid"]
                elif test_name_datasource == "POA": 
                    all_datasource = hidrep["sn"]
                elif test_name_datasource == "STT": 
                    all_datasource = hidrep["phi-type"]
                    include_map = {"ST": "s", "T": "#"}
                    include_tags = ["s", "#"]
                elif test_name_datasource == "AAIY_3": 
                    all_datasource = all_v2_names
                    this_offset = (0.4, 0.6)
                    include_map = {"AA": "AA", "IY": "IY"}
                    include_tags = ["AA", "IY"]
                elif test_name_datasource == "AAUW_3": 
                    all_datasource = all_v2_names
                    this_offset = (0.4, 0.6)
                    include_map = {"AA": "AA", "UW": "UW"}
                    include_tags = ["AA", "UW"]
                elif test_name_datasource == "IYUW_3": 
                    all_datasource = all_v2_names
                    this_offset = (0.4, 0.6)
                    include_map = {"IY": "IY", "UW": "UW"}
                elif test_name_datasource == "AAIY_1":
                    all_datasource = all_v1_names
                    this_offset = (0.4, 0.6)
                    include_map = {"AA": "AA", "IY": "IY"}
                elif test_name_datasource == "AAUW_1":
                    all_datasource = all_v1_names
                    this_offset = (0.4, 0.6)
                    include_map = {"AA": "AA", "UW": "UW"}
                elif test_name_datasource == "IYUW_1":
                    all_datasource = all_v1_names
                    this_offset = (0.4, 0.6)
                    include_map = {"IY": "IY", "UW": "UW"}
                elif test_name_datasource == "stop": 
                    all_datasource = hidrep["sn"]
                    merge_one_vector = True
                    this_offset = {st_condition_name: (0.3, 0.45), t_condition_name: (0.15, 0.2)}
                    this_auxon = "asp"
                elif test_name_datasource == "SSH":
                    # test whether the vowels can distinguish the S/SH contrast. 
                    if test_name_lookat == "second":
                        this_offset = (0.4, 0.6)
                    elif test_name_lookat == "third": 
                        this_offset = (0.1, 0.3)    # we only want to check the first part of the vowel (if it were a diphthong)
                    all_datasource = all_s_names
                else: 
                    raise ValueError("Datasource not included! ")
                
                # Select Vowels and Vowel Tags
                hidr_p, tags_p = get_toplot(hiddens=all_representations, 
                                                sepframes1=all_sepframes1,
                                                sepframes2=all_sepframes2,
                                                phi_types=all_phi_type,
                                                stop_names=all_datasource,
                                                offsets=this_offset, 
                                                contrast_in=test_name_label, 
                                                merge=merge_one_vector, 
                                                hidden_dim=hidden_dim_use, 
                                                lookat=test_name_lookat, 
                                                include_map=include_map, 
                                                aux_on=this_auxon)
                # combine them
                # hidr_cs, tags_cs = np.concatenate((hidr_p, hidr_pp, hidr_h), axis=0), np.concatenate((tags_p, tags_pp, tags_h), axis=0)
                hidr_cs, tags_cs = hidr_p, tags_p
                hidr_cs, tags_cs, nannum = postproc_standardize(hidr_cs, tags_cs, outlier_ratio=0, denan=True)
                print(f"{model_type}@{epoch} in run {run_number}: {nannum}")

                # Now we put in aspiration the contrast between pp and h
                for i in range(6): 
                    hidrs, tagss = separate_and_sample_data(data_array=hidr_cs, tag_array=tags_cs, sample_size=abx_num_samples, tags=include_tags)
                    abx_err01 = sym_abx_error(hidrs[0], hidrs[1], distance=euclidean_distance)
                    asp_list_runs.append(abx_err01)

            asp_list_epochs.append(asp_list_runs)

        asp_list_epochs = np.array(asp_list_epochs)
        asp_list_epochs = asp_list_epochs.transpose(1, 0)
        # plot_silhouette(asp_list_epochs, stop_list_epochs, os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"))
        plot_many([asp_list_epochs], ["ABX"], 
                  os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"), 
                  {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  y_range=(0, 1.0))
        # np.save(os.path.join(res_save_dir, test_name, f"04-save-ptk-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), stop_list_epochs)
        np.save(os.path.join(res_save_dir, test_name, f"07-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        print("Done.")

    elif test_name.split("-")[0] in ["ABXSomethingAll", "ABXSomethingCrossPhoneAll", "ABXpositionAll"]: 
        # 1 is euclidean, 2 is cosine distance
        # this one evaluates the copntrast between p, p(h) and (p)h.
        # 'dec-lin1' 'enc-rnn1-f' 'enc-rnn1-b' 'dec-rnn1-f' 'enc-rnn2-f' 'enc-rnn2-b' 'dec-rnn2-f' 
        layered_res = {}
        look_for_layer_path = test_name.split("-")[0][:-3] + "-" + test_name.split("-")[1] + "-" + test_name.split("-")[2] + "-" + test_name.split("-")[3]
        if zlevel.split("-")[0] == "ARC": 
            range_start = zlevel.split("-")[1]
            range_end = zlevel.split("-")[2]
            look_for_layer_path += f"-{range_start}-{range_end}"
        # deal with ori
        ori_path = os.path.join(res_save_dir, look_for_layer_path, f"07-save-ari-recon64-phi-{model_condition}-{strseq_learned_runs}-ori.npy")
        if os.path.exists(ori_path): 
            ori_res = np.load(ori_path)
        else: 
            raise ValueError("No ori path found.")
        for layer in ["hidrep", "attnout", "dec-lin1", "enc-lin1", 
                      "dec-rnn1-f", "enc-rnn1-f", "enc-rnn1-b",
                      "dec-rnn2-f", "enc-rnn2-f", "enc-rnn2-b", 
                      "dec-rnn3-f", "enc-rnn3-f", "enc-rnn3-b", 
                      "dec-rnn4-f", "enc-rnn4-f", "enc-rnn4-b", 
                      "dec-rnn5-f", "enc-rnn5-f", "enc-rnn5-b", ]: # "enc-lin1", 
            print(f"Processing {model_type} in layer {layer}...")
            asp_list_epochs = []
            layer_path = os.path.join(res_save_dir, look_for_layer_path, 
                                      f"07-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{layer}.npy")
            if os.path.exists(layer_path): 
                layer_res = np.load(layer_path)
            else: 
                print(f"Warning: {layer_path} not found. ")
                layer_res = np.zeros_like(ori_res)
            layered_res[layer] = layer_res

        layered_res["ori"] = ori_res

        # plot_many(list(layered_res.values()), list(layered_res.keys()), 
        #           os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"), 
        #           {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
        #           y_range=(0, 0.8), cloud=False)
        plot_many_plotly(list(layered_res.values()), list(layered_res.keys()), 
                  os.path.join(res_save_dir, test_name, f"08-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.html"), 
                  {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  y_range=(0, 0.5), cloud=True)
        # np.save(os.path.join(res_save_dir, test_name, f"04-save-ptk-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), stop_list_epochs)
        # np.save(os.path.join(res_save_dir, test_name, f"05-save-asp-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        # with open(os.path.join(res_save_dir, test_name, f"06-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.pkl"), "wb") as f: 
        #     pickle.dump(layered_res, f)
        print("Done.")

    elif test_name.split("-")[0] in ["ABXSomethingCrossPhone"]: 
        # This one is for the cross-phone ABX task.
        # For example, if I want to test the contrast between first and third position, I will use this one. 
        hidden_dim_use = hidden_dim
        for epoch in range(0, 101): 
            # 先循环epoch，再循环run
            stop_list_runs = []
            asp_list_runs = []
            print(f"Processing {model_type} in epoch {epoch}...")
            for run_number in learned_runs:

                test_name_lookats = test_name.split("-")[1].split("_")
                test_name_label = test_name.split("-")[2]
                test_name_datasource = test_name.split("-")[3]

                this_model_condition_dir = os.path.join(model_condition_dir, f"{run_number}")
                hidrep_handler = DictResHandler(whole_res_dir=this_model_condition_dir, 
                                    file_prefix=f"all-{epoch}")
                hidrep_handler.read()
                hidrep = hidrep_handler.res

                # select representation to work on
                all_representations, hidden_dim_use = get_representation(data_collection=hidrep, 
                                                         representation_select=zlevel, 
                                                         hidden_dim_required=hidden_dim)
                
                all_sepframes1 = hidrep["sep-frame1"]
                all_sepframes2 = hidrep["sep-frame2"]
                all_phi_type = hidrep["phi-type"]
                all_v1_names = hidrep["v1-name"]
                all_s_names = hidrep["sn"]
                all_v2_names = hidrep["vn"]


                include_map = None
                include_tags = None
                this_offset = (0.4, 0.6)
                this_auxon = None
                merge_one_vector = False

                if test_name_datasource in ["AA", "IY", "UW"]: 
                    all_datasource = all_v2_names
                    this_offsets = [(0.2, 0.6), (0.2, 0.6)]
                    include_maps = [{test_name_datasource:f"{test_name_datasource}_{lookat}"} for lookat in test_name_lookats]
                else: 
                    raise ValueError("Datasource not included! ")
                
                # Select Vowels and Vowel Tags
                hidr_1, tags_1 = get_toplot(hiddens=all_representations, 
                                                sepframes1=all_sepframes1,
                                                sepframes2=all_sepframes2,
                                                phi_types=all_phi_type,
                                                stop_names=all_datasource,
                                                offsets=this_offset, 
                                                contrast_in=test_name_label, 
                                                merge=merge_one_vector, 
                                                hidden_dim=hidden_dim_use, 
                                                lookat=test_name_lookats[0], 
                                                include_map=include_maps[0], 
                                                aux_on=this_auxon)
                hidr_2, tags_2 = get_toplot(hiddens=all_representations, 
                                                sepframes1=all_sepframes1,
                                                sepframes2=all_sepframes2,
                                                phi_types=all_phi_type,
                                                stop_names=all_datasource,
                                                offsets=this_offset, 
                                                contrast_in=test_name_label, 
                                                merge=merge_one_vector, 
                                                hidden_dim=hidden_dim_use, 
                                                lookat=test_name_lookats[1], 
                                                include_map=include_maps[1], 
                                                aux_on=this_auxon)
                # combine them
                hidr_cs, tags_cs = np.concatenate((hidr_1, hidr_2), axis=0), np.concatenate((tags_1, tags_2), axis=0)
                # hidr_cs, tags_cs = hidr_p, tags_p
                hidr_cs, tags_cs, nannum = postproc_standardize(hidr_cs, tags_cs, outlier_ratio=0, denan=True)
                print(f"{model_type}@{epoch} in run {run_number}: {nannum}")

                # Now we put in aspiration the contrast between pp and h
                for i in range(6): 
                    hidrs, tagss = separate_and_sample_data(data_array=hidr_cs, tag_array=tags_cs, sample_size=abx_num_samples, tags=include_tags)
                    abx_err01 = sym_abx_error(hidrs[0], hidrs[1], distance=euclidean_distance)
                    asp_list_runs.append(abx_err01)

            asp_list_epochs.append(asp_list_runs)

        asp_list_epochs = np.array(asp_list_epochs)
        asp_list_epochs = asp_list_epochs.transpose(1, 0)
        # plot_silhouette(asp_list_epochs, stop_list_epochs, os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"))
        plot_many([asp_list_epochs], ["ABX"], 
                  os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"), 
                  {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  y_range=(0, 1.0))
        # np.save(os.path.join(res_save_dir, test_name, f"04-save-ptk-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), stop_list_epochs)
        np.save(os.path.join(res_save_dir, test_name, f"07-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        print("Done.")

    elif test_name.split("-")[0] in ["ABXposition"]: 
        for epoch in range(0, 101): 
            # 先循环epoch，再循环run
            stop_list_runs = []
            asp_list_runs = []
            print(f"Processing {model_type} in epoch {epoch}...")
            for run_number in learned_runs:
                test_name_lookat = test_name.split("-")[1]
                test_name_label = test_name.split("-")[2]
                test_name_datasource = test_name.split("-")[3]

                this_model_condition_dir = os.path.join(model_condition_dir, f"{run_number}")
                hidrep_handler = DictResHandler(whole_res_dir=this_model_condition_dir, 
                                    file_prefix=f"all-{epoch}")
                hidrep_handler.read()
                hidrep = hidrep_handler.res
                # select representation to work on
                all_representations, hidden_dim_use = get_representation(data_collection=hidrep, 
                                                         representation_select=zlevel, 
                                                         hidden_dim_required=hidden_dim)
                
                all_sepframes1 = hidrep["sep-frame1"]
                all_sepframes2 = hidrep["sep-frame2"]
                all_phi_type = hidrep["phi-type"]
                all_v1_names = hidrep["v1-name"]
                all_s_names = hidrep["sn"]
                all_v2_names = hidrep["vn"]

                include_vowel_list = ["AA", "UW", "IY"]
                include_portion_list = ["START", "END"]
                include_maps = [{vowel:portion for vowel in include_vowel_list} for portion in include_portion_list]
                offsets = {"START": (0.15, 0.2), "END": (0.85, 0.9)} 
                if test_name_datasource == "vowel_1": 
                    all_datasource = all_v1_names
                elif test_name_datasource == "vowel_3": 
                    all_datasource = all_v2_names
                else: 
                    raise ValueError("Datasource not included! ")
                
                merge_one_vector = False
                # Select T (plosive)
                hidr_pp, tags_pp = get_toplot(hiddens=all_representations, 
                                                sepframes1=all_sepframes1,
                                                sepframes2=all_sepframes2,
                                                phi_types=all_phi_type,
                                                stop_names=all_datasource,
                                                offsets=offsets["START"], 
                                                contrast_in=test_name_label, 
                                                merge=merge_one_vector, 
                                                hidden_dim=hidden_dim_use, 
                                                lookat=test_name_lookat, 
                                                include_map=include_maps[0]) 
                # ENDING TOKENS
                hidr_h, tags_h = get_toplot(hiddens=all_representations, 
                                                sepframes1=all_sepframes1,
                                                sepframes2=all_sepframes2,
                                                phi_types=all_phi_type,
                                                stop_names=all_datasource,
                                                offsets=offsets["END"], 
                                                contrast_in=test_name_label, 
                                                merge=merge_one_vector, 
                                                hidden_dim=hidden_dim_use, 
                                                lookat=test_name_lookat, 
                                                include_map=include_maps[1])
                # combine them
                hidr_cs, tags_cs = np.concatenate((hidr_pp, hidr_h), axis=0), np.concatenate((tags_pp, tags_h), axis=0)
                hidr_cs, tags_cs, nannum = postproc_standardize(hidr_cs, tags_cs, outlier_ratio=0, denan=True)
                print(f"{model_type}@{epoch} in run {run_number}: {nannum}")

                distance_metrics = euclidean_distance

                # Now we put in aspiration the contrast between pp and h
                for i in range(6): 
                    hidrs, tagss = separate_and_sample_data(data_array=hidr_cs, tag_array=tags_cs, sample_size=abx_num_samples, tags=include_portion_list)
                    abx_err01 = sym_abx_error(hidrs[0], hidrs[1], distance=distance_metrics)
                    asp_list_runs.append(abx_err01)

            # stop_list_epochs.append(stop_list_runs) # 把每一个epoch的结果汇总，因为最后我们要保存结果，跑起来挺费时间的
            asp_list_epochs.append(asp_list_runs)

        # stop_list_epochs = np.array(stop_list_epochs)
        asp_list_epochs = np.array(asp_list_epochs)
        # stop_list_epochs = stop_list_epochs.transpose(1, 0)
        asp_list_epochs = asp_list_epochs.transpose(1, 0)
        np.save(os.path.join(res_save_dir, test_name, f"07-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        print("Done.")
    elif test_name.split("-")[0] in ["ABXpositionAll"]: 
        # 1 is euclidean, 2 is cosine distance
        # this one evaluates the copntrast between p, p(h) and (p)h.
        # 'dec-lin1' 'enc-rnn1-f' 'enc-rnn1-b' 'dec-rnn1-f' 'enc-rnn2-f' 'enc-rnn2-b' 'dec-rnn2-f' 
        look_for_layer_path = test_name.split("-")[0][:-3] + "-" + test_name.split("-")[1] + "-" + test_name.split("-")[2] + "-" + test_name.split("-")[3]
        layered_res = {}
        # deal with ori
        ori_path = os.path.join(res_save_dir, look_for_layer_path, f"05-save-asp-recon64-phi-{model_condition}-{strseq_learned_runs}-ori.npy")
        if os.path.exists(ori_path): 
            ori_res = np.load(ori_path)
        else: 
            raise ValueError("No ori path found.")
        for layer in ["hidrep", "attnout", "dec-lin1", "enc-lin1", 
                      "dec-rnn1-f", "enc-rnn1-f", "enc-rnn1-b",
                      "dec-rnn2-f", "enc-rnn2-f", "enc-rnn2-b", 
                      "dec-rnn3-f", "enc-rnn3-f", "enc-rnn3-b", 
                      "dec-rnn4-f", "enc-rnn4-f", "enc-rnn4-b", 
                      "dec-rnn5-f", "enc-rnn5-f", "enc-rnn5-b", ]: # "enc-lin1", 
            print(f"Processing {model_type} in layer {layer}...")
            asp_list_epochs = []
            layer_path = os.path.join(res_save_dir, look_for_layer_path, 
                                      f"05-save-asp-{model_type}-{model_condition}-{strseq_learned_runs}-{layer}.npy")
            if os.path.exists(layer_path): 
                layer_res = np.load(layer_path)
            else: 
                print(f"Warning: {layer_path} not found. ")
                layer_res = np.zeros_like(ori_res)
            layered_res[layer] = layer_res

        layered_res["ori"] = ori_res
        # plot_many(list(layered_res.values()), list(layered_res.keys()), 
        #           os.path.join(res_save_dir, test_name, f"03-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.png"), 
        #           {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
        #           y_range=(0, 0.8), cloud=False)
        plot_many_plotly(list(layered_res.values()), list(layered_res.keys()), 
                  os.path.join(res_save_dir, test_name, f"08-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.html"), 
                  {"xlabel": "Epochs", "ylabel": "ABX Error Rate", "title": f"ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  y_range=(0, 0.5), cloud=False)
        # np.save(os.path.join(res_save_dir, test_name, f"04-save-ptk-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), stop_list_epochs)
        # np.save(os.path.join(res_save_dir, test_name, f"05-save-asp-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        # with open(os.path.join(res_save_dir, test_name, f"06-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.pkl"), "wb") as f: 
        #     pickle.dump(layered_res, f)
        print("Done.")
    elif test_name.split("-")[0] in ["FinalEpochs"]: 
        if zlevel == "VC": 
            look_for_layer_path = "ABXSomething-vowel-vowel-vowel"
            resnum = "07"
            resname = "ari"
        elif zlevel == "POS": 
            look_for_layer_path = "ABXposition-vowel-vowel-vowel"
            resnum = "05"
            resname = "asp"
        elif zlevel == "STOPPOA": 
            look_for_layer_path = "ABXSomething-stop-data-stop"
            resnum = "07"
            resname = "ari"
        elif zlevel.split("-")[0] == "PARC": 
            _, a, b = zlevel.split("-")
            look_for_layer_path = f"ABXSomethingPro-stop-data-aspirationRangeComp-{a}-{b}"
            resnum = "07"
            resname = "ari"
        elif zlevel.split("-")[0] == "ARC": 
            _, a, b = zlevel.split("-")
            look_for_layer_path = f"ABXSomething-stop-data-aspirationRangeComp-{a}-{b}"
            resnum = "07"
            resname = "ari"
        elif zlevel == "PPP": 
            look_for_layer_path = "abx-pph"
            resnum = "04"
            resname = "ptk"
        elif zlevel == "PPH": 
            look_for_layer_path = "abx-pph"
            resnum = "05"
            resname = "asp"
        elif zlevel == "STT": 
            look_for_layer_path = "ABXSomething-pre-pre-STT"
            resnum = "07"
            resname = "ari"
        elif zlevel == "GENDER": 
            look_for_layer_path = "ABXSomething-vowel-vowel-gender"
            resnum = "07"
            resname = "ari"
        elif zlevel == "SPEAKER": 
            look_for_layer_path = "ABXSomething-vowel-vowel-speaker"
            resnum = "07"
            resname = "ari"
        elif zlevel == "ASPALLSTOP": 
            look_for_layer_path = "ABXSomething-stop-data-aspirationTotal"
            resnum = "07"
            resname = "ari"
        
        dimensions = [4, 8, 16, 32, 48, 64]
        layered_res = {}
        ori_path = os.path.join(res_save_dir, look_for_layer_path, f"{resnum}-save-{resname}-recon64-phi-{model_condition}-{strseq_learned_runs}-ori.npy")
        # read ori
        if os.path.exists(ori_path): 
            ori_res = np.load(ori_path)
            # shape: (runs, epochs)
        else: 
            raise ValueError("No ori path found.")
        
        ori_val = ori_res[:, 95:100].reshape(-1)
        
        for layer in ["hidrep", "attnout", "dec-lin1", "enc-lin1", 
                    "dec-rnn1-f", "enc-rnn1-f", "enc-rnn1-b",
                    "dec-rnn2-f", "enc-rnn2-f", "enc-rnn2-b", 
                    "dec-rnn3-f", "enc-rnn3-f", "enc-rnn3-b", 
                    "dec-rnn4-f", "enc-rnn4-f", "enc-rnn4-b", 
                    "dec-rnn5-f", "enc-rnn5-f", "enc-rnn5-b", ]: # "enc-lin1", 
            layer_res_with_dims = []
            for dimension in dimensions: 
                model_type = f"recon{dimension}-phi"
                print(f"Processing {model_type} in layer {layer}...")
                asp_list_epochs = []
                layer_path = os.path.join(res_save_dir, look_for_layer_path, 
                                        f"{resnum}-save-{resname}-{model_type}-{model_condition}-{strseq_learned_runs}-{layer}.npy")
                if os.path.exists(layer_path): 
                    layer_res = np.load(layer_path)
                else: 
                    print(f"Warning: {layer_path} not found. ")
                    layer_res = np.zeros_like(ori_res)
                layer_res_with_dims.append(layer_res[:, 95:100].reshape(-1)-ori_val)
                # [dim, runs]
            layered_res[layer] = np.array(layer_res_with_dims).transpose(1, 0)
            # layered_res[layer] = layer_res[:, 90:100].reshape(-1)

        # layered_res["ori"] = np.repeat(ori_res[:, 95:100].reshape(-1)[:, np.newaxis], len(dimensions), axis=1)

        plot_many_plotly_errbar(list(layered_res.values()), list(layered_res.keys()), 
                  os.path.join(res_save_dir, test_name, f"08-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.html"), 
                  {"xlabel": "Dimension", "ylabel": "ABX Error Rate (Epochs 95-100)", "title": f"Final Epochs ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  x_list=[4, 8, 16, 32, 48, 64], y_range=(-0.5, 0.5), cloud=True)
        # np.save(os.path.join(res_save_dir, test_name, f"04-save-ptk-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), stop_list_epochs)
        # np.save(os.path.join(res_save_dir, test_name, f"05-save-asp-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.npy"), asp_list_epochs)
        # with open(os.path.join(res_save_dir, test_name, f"06-save-ari-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.pkl"), "wb") as f: 
        #     pickle.dump(layered_res, f)
        print("Done.")
    elif test_name.split("-")[0] in ["FinalEpochsDimneutral"]: 
        def restructure_data(data_dict, dimension_retain_range=(2, 6)):
            representation_types = list(next(iter(data_dict.values())).keys())  # Extract all representation types
            test_types = list(data_dict.keys())  # Extract all test types

            # Prepare lists for the output
            arrays_list = []  # Will hold the (samples, dimensions, testtypes) arrays
            rep_type_keys = []  # Store corresponding representation type keys

            # Iterate over each representation type to collect data across all test types
            for rep_type in representation_types:
                collected_data = [data_dict[test_type][rep_type] for test_type in test_types]
                
                # Stack along a new axis for test type: shape (samples, dimensions, testtypes)
                combined_array = np.stack(collected_data, axis=-1)
                combined_array = combined_array[:, dimension_retain_range[0]:dimension_retain_range[1], :].reshape(-1, len(test_types))
                arrays_list.append(combined_array)
                rep_type_keys.append(rep_type)

            return arrays_list, rep_type_keys, test_types
        # in this we want to ignore dimensionality and thus we can plot all tests together
        alltestres = {}
        for zlevel in ["VC", "PPP", "PPH", "STT"]: 
            if zlevel == "VC": 
                look_for_layer_path = "ABXSomething-vowel-vowel-vowel"
                resnum = "07"
                resname = "ari"
            elif zlevel == "PPP": 
                look_for_layer_path = "abx-pph"
                resnum = "04"
                resname = "ptk"
            elif zlevel == "PPH": 
                look_for_layer_path = "abx-pph"
                resnum = "05"
                resname = "asp"
            elif zlevel == "STT": 
                look_for_layer_path = "ABXSomething-pre-pre-STT"
                resnum = "07"
                resname = "ari"
        
            dimensions = [4, 8, 16, 32, 48, 64]
            layered_res = {}
            ori_path = os.path.join(res_save_dir, look_for_layer_path, f"{resnum}-save-{resname}-recon64-phi-{model_condition}-{strseq_learned_runs}-ori.npy")
            # read ori
            if os.path.exists(ori_path): 
                ori_res = np.load(ori_path)
                # shape: (runs, epochs)
            else: 
                raise ValueError("No ori path found.")
            
            for layer in ["hidrep", "attnout", "dec-lin1", "enc-lin1", 
                        "dec-rnn1-f", "enc-rnn1-f", "enc-rnn1-b",
                        "dec-rnn2-f", "enc-rnn2-f", "enc-rnn2-b", 
                        "dec-rnn3-f", "enc-rnn3-f", "enc-rnn3-b", 
                        "dec-rnn4-f", "enc-rnn4-f", "enc-rnn4-b", 
                        "dec-rnn5-f", "enc-rnn5-f", "enc-rnn5-b", ]: # "enc-lin1", 
                layer_res_with_dims = []
                for dimension in dimensions: 
                    model_type = f"recon{dimension}-phi"
                    print(f"Processing {model_type} in layer {layer}...")
                    asp_list_epochs = []
                    layer_path = os.path.join(res_save_dir, look_for_layer_path, 
                                            f"{resnum}-save-{resname}-{model_type}-{model_condition}-{strseq_learned_runs}-{layer}.npy")
                    if os.path.exists(layer_path): 
                        layer_res = np.load(layer_path)
                    else: 
                        print(f"Warning: {layer_path} not found. ")
                        layer_res = np.zeros_like(ori_res)
                    layer_res_with_dims.append(layer_res[:, 95:100].reshape(-1))
                    # [dim, runs]
                layered_res[layer] = np.array(layer_res_with_dims).transpose(1, 0)
                # layered_res[layer] = layer_res[:, 90:100].reshape(-1)

            layered_res["ori"] = np.repeat(ori_res[:, 95:100].reshape(-1)[:, np.newaxis], len(dimensions), axis=1)

            alltestres[zlevel] = layered_res

        # plot all tests together
        res_list, rep_type_keys, test_types = restructure_data(alltestres, dimension_retain_range=(2, 6))

        plot_many_plotly_errbar(list(res_list), list(rep_type_keys), 
                  os.path.join(res_save_dir, test_name, f"08-stat-{model_type}-{model_condition}-{strseq_learned_runs}-{zlevel}.html"), 
                  {"xlabel": "Dimension", "ylabel": "ABX Error Rate (Epochs 95-100)", "title": f"Final Epochs ABX Error Rate for {model_type} in {model_condition} at {zlevel}"}, 
                  x_list=test_types, y_range=(0, 0.5), cloud=True)
        print("Done.")